export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_WALLPAPER = 'LOAD_WALLPAPER';
export const LOAD_WALLPAPERS = 'LOAD_WALLPAPERS';
export const LIKE_WALLPAPER = 'LIKE_WALLPAPER';
export const LIKE_WALLPAPER_FROM_DETAIL = 'LIKE_WALLPAPER_FROM_DETAIL';