// WALLPAPER
export const LOAD_WALLPAPERS = 'LOAD_WALLPAPERS';
export const LOAD_WALLPAPERS_SUCCESS = 'LOAD_WALLPAPERS_SUCCESS';
export const LOAD_WALLPAPERS_ERROR = 'LOAD_WALLPAPERS_ERROR';
export const SET_TOTAL_WALLPAPER = 'SET_TOTAL_WALLPAPER';
export const SET_PAGE = 'SET_PAGE';
export const UPDATE_WALLPAPER = 'UPDATE_WALLPAPER';
export const UPDATE_WALLPAPER_SUCCESS = 'UPDATE_WALLPAPER_SUCCESS';
export const UPDATE_WALLPAPER_ERROR = 'UPDATE_WALLPAPER_ERROR';

// IPHONE MODEL
export const LOAD_IPHONE_MODELS = 'LOAD_IPHONE_MODELS';
export const LOAD_IPHONE_MODELS_SUCCESS = 'LOAD_IPHONE_MODELS_SUCCESS';
export const LOAD_IPHONE_MODELS_ERROR = 'LOAD_IPHONE_MODELS_ERROR';
export const SET_IPHONE_MODELS = 'SET_IPHONE_MODELS';

// CATEGORY
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';
export const LOAD_CATEGORY_BY_NAME = 'LOAD_CATEGORY_BY_NAME';
export const GET_TOTAL_WALLPAPER = 'GET_TOTAL_WALLPAPER';
export const GET_TOTAL_WALLPAPER_SUCCESS = 'GET_TOTAL_WALLPAPER_SUCCESS';
export const GET_TOTAL_WALLPAPER_ERROR = 'GET_TOTAL_WALLPAPER_ERROR';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const LOAD_CATEGORY_BY_NAME_ERROR = 'LOAD_CATEGORY_BY_NAME_ERROR';

// GLOBAL
export const SET_IPHONE_MODEL = 'SET_IPHONE_MODEL';
export const SET_SCREEN_SIZE = 'SET_SCREEN_SIZE';
export const SET_SELECTED_IPHONE_MODEL = 'SET_SELECTED_IPHONE_MODEL';
export const LOAD_IPHONE_MODEL = 'LOAD_IPHONE_MODEL';
export const LOAD_IPHONE_MODEL_SUCCESS = 'LOAD_IPHONE_MODEL_SUCCESS';
export const LOAD_IPHONE_MODEL_ERROR = 'LOAD_IPHONE_MODEL_ERROR';
